[package]
name = "booktop"
version = "0.0.1"
authors = ["Dominic Branford"]
edition = "2021"

[dependencies]
clap = { version="3.1", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
