[package]
name = "booktop"
version = "0.0.1"
authors = ["Dominic Branford"]
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.27.0"
rand = "0.8"
ratatui = "0.26"
serde = { version = "1", features = ["derive"] }
serde_yaml = { version = "0.9" }
